[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "autodoc2"

[project]
name = "py2fern"
dynamic = ["version", "description"]
authors = [{name = "Ryan Stephen", email = "ryanstep@buildwithfern.com"}]
license = {file = "LICENSE"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
readme = "README.md"
keywords = ["python", "documentation", "fern", "api", "static-analysis"]
urls = {Home = "https://github.com/fern-api/py2fern"}
requires-python = ">=3.8"
dependencies = [
    "astroid>=2.7,<4",
    "tomli; python_version<'3.11'", 
    "typing-extensions",
    "typer[all]",
    "PyYAML"
]

[project.optional-dependencies]
testing = [
    "pytest",
    "pytest-regressions", 
    "pytest-cov",
]

[project.scripts]
py2fern = "autodoc2.cli:app_main"

[tool.ruff.lint]
extend-select = [
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "I",    # isort
    "ICN",  # flake8-import-conventions
    "ISC",  # flake8-implicit-str-concat
    "N",    # pep8-naming
    "PERF", # perflint (performance anti-patterns)
    "PGH",  # pygrep-hooks
    "PIE",  # flake8-pie
    "PTH",  # flake8-use-pathlib
    "RUF",  # Ruff-specific rules
    "SIM",  # flake8-simplify
    "UP",   # pyupgrade
    "T20",  # flake8-print
]
extend-ignore = ["ISC001", "PERF203", "PGH003"]

[tool.ruff.lint.per-file-ignores]
# ignore: Do not perform function call `typer.Option` in argument defaults
"src/autodoc2/cli.py" = ["B008"]
"tests/test_analyse_module.py" = ["E501"]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.mypy]
show_error_codes = true
strict = true
exclude = ['^tests/.*']

[[tool.mypy.overrides]]
module = [
    "astroid.*",  # https://github.com/PyCQA/astroid/issues/1287
    "tomllib.*",
    "tomli.*",
]
ignore_missing_imports = true


[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py38

[testenv]
usedevelop = true

[testenv:py{38,39,310,311}]
extras =
    testing
commands = pytest {posargs}

[testenv:cli-py{38,39,310,311}]
commands = py2fern {posargs}
"""
